### ISSUE TITLE
convert odt, md files on the fly through pandoc

### ISSUE THREAD

**Issue by swirly** [ClementGre/PDF4Teachers#67]
**Is your feature request related to a problem? Please describe.**
Not really a problem. Sometimes, my pupils send odt or markdown files instead of pdf. So this can not be opened in pdf4teachers.

**Describe the solution you'd like**
If [pandoc](https://pandoc.org/) is installed on system, use pandoc to convert easely most of type of files to pdf. 

**Describe alternatives you've considered**
As alawys, I can script myself a odt, md to pdf using pandoc and bash, but it would be nice if this was integrated into pdf4teachers, just through a call to pandoc. The pandoc path should be a option of pandoc.

Note that *pandoc* can be installed on Mac Os, Linux and windows.

**Comment by ClementGre** [comment]
To solve this issue, we will need to use an API since it is very complex to transform an odt into pdf, (or even markdown).

Pandoc is a very wide convertor, and it would be great to integrate it in the application. I saw this Java API [https://bitbucket.org/leito/universal-document-converter/src/master/](Universal Document Converter) which could allow me to use Pandoc in Java. I will test it and I keep you updated.

This API is just an invoker of Pandoc so pandoc will need to be installed before of your computer.

**Comment by ClementGre** [comment]
Hi,

Universal Document Converter will ask to install a whole LaTeX app in addition to Pandoc so I think it would be better to let you use the command line tool.

Adding a full-library to allow PDF4Teachers to convert files by itself would need a lot of larges API, and this is not a good idea.
I think the best way to solve this problem is to ask your pupils to send you PDF (or images), and nothing else.

\- Clément G.
