### ISSUE TITLE
Using LaTeX as default for Text elements

### ISSUE THREAD

**Issue by CardanoStakeGit** [ClementGre/PDF4Teachers#74]
- [x] I checked this feature was not already requested [here](https://github.com/clementgre/PDF4Teachers/issues?q=is%3Aissue+milestone%3A%22Release+1.2.1%22+label%3A%22enhancement%22+)

**Is your feature request related to a problem? Please describe.**
Writing all LaTeX will give good oportunities for bold, cursive, special characters etc. It's just a 'better' way of writing I think.
I don't know how you have done it (yes, I know it's open source), but I suppose you do have a full LaTeX intepreter anyway.
And it might solve the issue with newline (https://github.com/ClementGre/PDF4Teachers/issues/73). I do understand that not everyone would prefer or know how to use LaTeX. So somehow it has to be customizable. I would like it to be in the settings, so that I just automatically always write in LaTeX style.
P.S. I would prefer to keep the fontsize and color change possible like it is now!

**Describe the solution you'd like**
In settings choose if you wan't to write "plain" or "LaTeX".

**Describe alternatives you've considered**

**Additional context**
This might also be a solution to my bug-report: https://github.com/ClementGre/PDF4Teachers/issues/73

**Comment by ClementGre** [comment]
Hi CardanoStakeGit,
this is a good idea for people who only use LaTeX like you.

In fact, PDF4Teachers just use a LaTeX interpreter that generates images from LaTeX. For the support of merging "plain text" and LaTeX, the app just put the letters that are not into $$, between "\text{" and "}" (adding \\ before the special chars).

I think I can allow the user to enable LaTeX by default so the text will be by default considered between $$, but this can cause some problems if the user enables this option and re-open editions that was edited without the option.
An alternative would be to just add silently $$ before and after text when creating an element, and I have to find a way to hide theses chars into the text field. I think this is realizable, I'll keep you updated !

Thank you, Clement

**Comment by ClementGre** [comment]
Hi @CardanoStakeGit,

I just implemented this feature: in the settings, you can choose to use LaTeX as default for text elements instead of plain text.

Good news, you can enable/disable this option without breaking anything. In fact, this option just adds silently $$ between all text elements, and it hides the first $$ in the text field. Therefore, if you disable the option, you will just see the first $$ of LaTeX elements, and you will not see anymore the first $$ of plain text elements, and vice versa when you enables the option.

Thank you, Clément.
