### ISSUE TITLE
Font size option for menubar

### ISSUE THREAD

**Issue by raphaelfournier** [ClementGre/PDF4Teachers#91]
My laptop display is a 14", with fullHD (1920x1080) resolution. The menus in the pdf4teachers app are very small (looks like in the range 12/14 range). I am short-sighted and the base font size for my apps are more 16-18pt minimum. I would like a "preference" option to customize that. 

I tried setting up several options in /etc/environment, with the `JAVA_TOOL_OPTIONS`, which are said to be read by pdf4teachers (at least it says so at startup). I could not find the right one to bump the font size.
I found the base.css file, but I have yet to build the full development environment to build a custom version of pdf4teachers with a different default font size. However, those two options would only work for me, while it should be useful for others users to be able to change that.

**Comment by ClementGre** [comment]
Hi @raphaelfournier,

unfortunately, it would be complicate to allow the user to change the font size on the fly because it would create layout issues.

It is not easier to zoom the whole app, but I had to develop this feature to fix some HiDPI issues on some Gnome systems.
Therefore, you will be able to zoom the whole app in the next release, see https://github.com/ClementGre/PDF4Teachers/issues/63#issuecomment-834030004.

I think this feature will fix your issue.
Thank you, Clément.
